apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-pipelines-canary-k8s
  labels:
    app: azure-pipelines-canary-k8s
spec:
  replicas: 4
  selector:
    matchLabels:
      app: azure-pipelines-canary-k8s
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: azure-pipelines-canary-k8s
    spec:
      containers:
      - name: azure-pipelines-canary-k8s
        #replace <foobar> with your container registry. Example: contosodemo.azurecr.io
        image: azmjlt0001cr.azurecr.io/azure-pipelines-canary-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
