apiVersion: v1
kind: Service
metadata:
  name: azure-pipelines-canary-k8s
  labels:
    app: azure-pipelines-canary-k8s
spec:
  selector:
    app: azure-pipelines-canary-k8s
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
